CREATE TABLE IF NOT EXISTS fixed_extension (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    extension VARCHAR(20) NOT NULL,
    blocked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT uq_fixed_extension UNIQUE (extension)
);

CREATE TABLE IF NOT EXISTS custom_extension (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    extension VARCHAR(20) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_custom_extension UNIQUE (extension)
);
